# Generated by Django 3.2.12 on 2024-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='profileImage',
            field=models.ImageField(default='default/user.png', upload_to='user_profile_images/'),
        ),
    ]
