# Generated by Django 3.2.12 on 2024-04-14 04:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccountmodel_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='profileImage',
            field=models.ImageField(default='default/user.png', upload_to=accounts.models.rename_profile_image),
        ),
    ]
