# Generated by Django 3.2.12 on 2024-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20240414_0550'),
        ('accounts', '0003_alter_useraccountmodel_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='following',
            field=models.ManyToManyField(related_name='followedBy', to='songs.ArtistModel'),
        ),
    ]
