# Generated by Django 3.2.12 on 2024-04-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccountmodel_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountmodel',
            name='following',
        ),
    ]
