# Generated by Django 3.2.12 on 2024-04-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='song',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
