# Generated by Django 3.2.12 on 2024-04-14 04:38

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20240414_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='thumbnail',
            field=models.ImageField(default='default/user.png', upload_to=songs.models.rename_thumbnail),
        ),
    ]
