# Generated by Django 3.2.12 on 2024-04-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_songmodel_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='thumbnail',
            field=models.ImageField(default='default/user.png', upload_to='song_thumbnails'),
        ),
    ]
