# Generated by Django 3.2.12 on 2024-04-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20240419_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.artistmodel'),
        ),
    ]
