# Generated by Django 3.2.12 on 2024-04-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_moviesmodel_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.moviesmodel'),
        ),
    ]
